[service]
name = "postgresql"
exec = "/usr/bin/postgres -D /var/lib/postgres/data"
restart = "on-failure"
user = "postgres"

[deps]
after = ["udev-trigger"]

[ready]
strategy = "socket"
path = "/run/postgresql/.s.PGSQL.5432"

[resources]
oom_score_adj = -500
