[service]
name = "avahi"
exec = "/usr/bin/avahi-daemon --no-drop-root"
restart = "never"

[deps]
needs = ["dbus"]
after = ["udev-trigger"]

[ready]
strategy = "socket"
path = "/run/avahi-daemon/socket"
