[service]
name = "containerd"
exec = "/usr/bin/containerd"
restart = "on-failure"

[deps]
after = ["udev-trigger"]

[ready]
strategy = "socket"
path = "/run/containerd/containerd.sock"

[resources]
oom_score_adj = -500
