[service]
name = "tor"
exec = "/usr/bin/tor --RunAsDaemon 0"
restart = "on-failure"
user = "tor"

[deps]
after = ["networkmanager", "nftables"]

[ready]
strategy = "pidfile"
path = "/run/tor/tor.pid"
