[service]
name = "beta"
exec = "/home/keegan/Projects/flint-init/services/diamond/scripts/beta.sh"

[deps]
after = ["alpha"]
needs = ["alpha"]

[ready]
strategy = "pidfile"
path = "/tmp/flint-test/diamond/beta.pid"
