[service]
name = "networkmanager"
exec = "/usr/bin/NetworkManager --pid-file=/run/NetworkManager/NetworkManager.pid"
restart = "on-failure"

[deps]
after = ["nm-priv-helper"]
needs = ["nm-priv-helper"]

[ready]
strategy = "pidfile"
path = "/run/NetworkManager/NetworkManager.pid"
